pipeline {
  agent any
  tools {
    nodejs 'v14.20.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Instalar dependencias') {
      steps {
        sh 'cd jenkins-tests && npm i'
      }
    }
    stage('Ejecutar pruebas') {
      steps {
        sh 'cd jenkins-tests && npm t'
      }
    }
  }
}
