pipeline {
  agent any

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  environment {
    ARTIFACT_ID = "scastellanos77/webapp:${env.BUILD_NUMBER}"
  }

  stages {
    stage('Compilar') {
      steps {
        script {
          dir("webapp") {
            dockerImage = docker.build "${env.ARTIFACT_ID}"
          }
        }
      }
    }
    stage('Ejecutar Pruebas') {
      steps {
        sh "docker run ${dockerImage.id} npm test"
        sh "docker ps -a"
      }
    }
    stage('Publicar') {
      when {
        branch 'master'
      }
      steps {
        script {
          docker.withRegistry("", "DockerHubCredentials") {
            dockerImage.push()
          }
        }
      }
    }
    stage('Agendar Staging Deployment') {
      when {
        branch 'master'
      }
      steps {
        sh "docker ps -a"
        build job: 'deploy-webapp-staging', parameters: [string(name: 'ARTIFACT_ID', value: "${env.ARTIFACT_ID}")], wait: false
      }
    }
  }
}

